print(f'5 * 2 = {5*2}')
print(4 + 2 * 5)
print('Ab' + '2')
print(10/2)
print(11//3)
print(11 % 3)
print(2 ** 0.5)

a = int(input('Egyik szám: '))
b = int(input('Másik szám: '))
print(f'{a} +{b} = {a+b}')