import cuccok
forrás = open('6b.txt', mode='r', encoding='utf-8')
hernyo = open('cucc.py', mode='r', encoding='utf-8')
cuccok.vonal()
hely = []
idopont = []

forrás.readline()
for sor in forrás:
    adat = sor.strip().split(' ')
    hely.append(int(adat[0]))
    idopont.append(int(adat[1]) * 60 + int(adat[2]))
forrás.close()

leghosszabb_id = 0
leghosszabb_ido = idopont[1] - idopont[0]
for i in range(len(hely)-1):
    if idopont[i+1] - idopont[i] > leghosszabb_ido:
        leghosszabb_id = i
        leghosszabb_ido = idopont[i+1] - idopont[i]

ötvenespontok = 0
for i in range(len(hely)):
    if hely[i] == 50:
        ötvenespontok += 1

print(f'{ötvenespontok} adat tartozik az 50es mérési ponthoz')
cuccok.vonal()
van = False
bekért = int(input('időpont:'))
for i in range(len(idopont)):
    if i == bekért:
        van = True
if van == True:
    print('van ebben az időpontban adat')
else:
    print('nincs ebben az időpontban adat')
cuccok.vonal()
volt = False
for i in range(len(idopont)-1):
    if idopont[i] == idopont[i+1]:
        volt = True
if volt == True:
    print('volt olyan időpont ahol kétszer mértek')
if volt == False:
    print('nem volt olyan időpont ahol kétszer mértek')
cuccok.vonal()

számláló = []
I = 0
II = 0
III = 0
IIII = 0
IIIII = 0
IIIIII = 0
IIIIIII = 0
IIIIIIII = 0
IIIIIIIII = 0
IIIIIIIIII = 0
IIIIIIIIIII = 0
IIIIIIIIIIII = 0
IIIIIIIIIIIII = 0
IIIIIIIIIIIIII = 0
IIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0

for i in range(len(hely)):
    if 1 == i:
      I += 1
    elif 2 == i:
      II += 1
    elif 3 == i:
      III += 1
    elif 4 == i:
      IIII += 1
    elif 5 == i:
      IIIII += 1
    elif 6 == i:
      IIIIII += 1
    elif 7 == i:
      IIIIIII += 1
    elif 8 == i:
      IIIIIIII += 1
    elif 9 == i:
      IIIIIIIII += 1
    elif 10 == i:
      IIIIIIIIII += 1
    elif 11 == i:
      IIIIIIIIIII += 1
    elif 12 == i:
      IIIIIIIIIIII += 1
    elif 13 == i:
      IIIIIIIIIIIII += 1
    elif 14 == i:
      IIIIIIIIIIIIII += 1
    elif 15 == i:
      IIIIIIIIIIIIIII += 1
    elif 16 == i:
      IIIIIIIIIIIIIIII += 1
    elif 17 == i:
      IIIIIIIIIIIIIIIII += 1
    elif 18 == i:
      IIIIIIIIIIIIIIIIII += 1
    elif 19 == i:
      IIIIIIIIIIIIIIIIIII += 1
    elif 20 == i:
      IIIIIIIIIIIIIIIIIIII += 1
    elif 21 == i:
      IIIIIIIIIIIIIIIIIIIII += 1
    elif 22 == i:
      IIIIIIIIIIIIIIIIIIIIII += 1
    elif 23 == i:
      IIIIIIIIIIIIIIIIIIIIIII += 1
    elif 24 == i:
      IIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 25 == i:
      IIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 26 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 27 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 28 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 29 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 30 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 31 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 32 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 33 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 34 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 35 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 36 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 37 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 38 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 39 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 40 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 41 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 42 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 43 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 44 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 45 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 46 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 47 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 48 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 49 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 50 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 51 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 52 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 53 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 54 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 55 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 56 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 57 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 58 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 59 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 60 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 61 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 62 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 63 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 64 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 65 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 66 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 67 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 68 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 69 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 70 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 71 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 72 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 73 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 74 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 75 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 76 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 77 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 78 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 79 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 80 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 81 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 82 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 83 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 84 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 85 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 86 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 87 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 88 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 89 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 90 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 91 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 92 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 93 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 94 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 95 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 96 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 97 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 98 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 99 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 100 == i:
      IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1

print(f"{I}")
print(f"{II}")
print(f"{III}")
print(f"{IIII}")
print(f"{IIIII}")
print(f"{IIIIII}")
print(f"{IIIIIII}")
print(f"{IIIIIIII}")
print(f"{IIIIIIIII}")
print(f"{IIIIIIIIII}")
print(f"{IIIIIIIIIII}")
print(f"{IIIIIIIIIIII}")
print(f"{IIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}")
