import cuccok
forrás = open('fölös/6b.txt', mode='r', encoding='utf-8')
hernyo = open('cucc.py', mode='r', encoding='utf-8')
cuccok.vonal()
hely = []
idopont = []

forrás.readline()
for sor in forrás:
    adat = sor.strip().split(' ')
    hely.append(int(adat[0]))
    idopont.append(int(adat[1]) * 60 + int(adat[2]))
forrás.close()

leghosszabb_id = 0
leghosszabb_ido = idopont[1] - idopont[0]
for i in range(len(hely)-1):
    if idopont[i+1] - idopont[i] > leghosszabb_ido:
        leghosszabb_id = i
        leghosszabb_ido = idopont[i+1] - idopont[i]

ötvenespontok = 0
for i in range(len(hely)):
    if hely[i] == 50:
        ötvenespontok += 1

print(f'{ötvenespontok} adat tartozik az 50es mérési ponthoz')
cuccok.vonal()
van = False
bekért = int(input('időpont:'))
for i in range(len(idopont)):
    if i == bekért:
        van = True
if van == True:
    print('van ebben az időpontban adat')
else:
    print('nincs ebben az időpontban adat')
cuccok.vonal()
volt = False
for i in range(len(idopont)-1):
    if idopont[i] == idopont[i+1]:
        volt = True
if volt == True:
    print('volt olyan időpont ahol kétszer mértek')
if volt == False:
    print('nem volt olyan időpont ahol kétszer mértek')
cuccok.vonal()

számláló = []
I = 0
II = 0
III = 0
IIII = 0
IIIII = 0
IIIIII = 0
IIIIIII = 0
IIIIIIII = 0
IIIIIIIII = 0
IIIIIIIIII = 0
IIIIIIIIIII = 0
IIIIIIIIIIII = 0
IIIIIIIIIIIII = 0
IIIIIIIIIIIIII = 0
IIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0

for i in range(len(hely)):
    if 1 == hely[i]:
        I += 1
    elif 2 == hely[i]:
        II += 1
    elif 3 == hely[i]:
        III += 1
    elif 4 == hely[i]:
        IIII += 1
    elif 5 == hely[i]:
        IIIII += 1
    elif 6 == hely[i]:
        IIIIII += 1
    elif 7 == hely[i]:
        IIIIIII += 1
    elif 8 == hely[i]:
        IIIIIIII += 1
    elif 9 == hely[i]:
        IIIIIIIII += 1
    elif 10 == hely[i]:
        IIIIIIIIII += 1
    elif 11 == hely[i]:
        IIIIIIIIIII += 1
    elif 12 == hely[i]:
        IIIIIIIIIIII += 1
    elif 13 == hely[i]:
        IIIIIIIIIIIII += 1
    elif 14 == hely[i]:
        IIIIIIIIIIIIII += 1
    elif 15 == hely[i]:
        IIIIIIIIIIIIIII += 1
    elif 16 == hely[i]:
        IIIIIIIIIIIIIIII += 1
    elif 17 == hely[i]:
        IIIIIIIIIIIIIIIII += 1
    elif 18 == hely[i]:
        IIIIIIIIIIIIIIIIII += 1
    elif 19 == hely[i]:
        IIIIIIIIIIIIIIIIIII += 1
    elif 20 == hely[i]:
        IIIIIIIIIIIIIIIIIIII += 1
    elif 21 == hely[i]:
        IIIIIIIIIIIIIIIIIIIII += 1
    elif 22 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIII += 1
    elif 23 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIII += 1
    elif 24 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 25 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 26 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 27 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 28 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 29 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 30 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 31 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 32 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 33 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 34 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 35 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 36 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 37 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 38 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 39 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 40 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 41 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 42 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 43 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 44 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 45 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 46 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 47 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 48 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 49 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 50 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 51 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 52 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 53 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 54 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 55 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 56 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 57 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 58 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 59 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 60 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 61 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 62 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 63 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 64 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 65 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 66 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 67 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 68 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 69 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 70 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 71 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 72 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 73 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 74 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 75 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 76 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 77 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 78 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 79 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 80 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 81 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 82 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 83 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 84 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 85 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 86 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 87 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 88 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 89 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 90 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 91 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 92 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 93 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 94 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 95 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 96 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 97 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 98 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 99 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
    elif 100 == hely[i]:
        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1

print(f"{I}db mérés az adott helyen")
print(f"{II}db mérés az adott helyen")
print(f"{III}db mérés az adott helyen")
print(f"{IIII}db mérés az adott helyen")
print(f"{IIIII}db mérés az adott helyen")
print(f"{IIIIII}db mérés az adott helyen")
print(f"{IIIIIII}db mérés az adott helyen")
print(f"{IIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")
print(f"{IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII}db mérés az adott helyen")

válasz = input('igen/nem:')


    from random import random
    import tkinter as tk


    def on_closing(r):
        r.destroy()

        for i in range(2):
            window()


    def window():
        root = tk.Toplevel()
        root.title("Hydra")

        # Position the window
        w = 450
        h = 250
        sw = root.winfo_screenwidth()
        sh = root.winfo_screenheight()
        x = random() * sw
        y = random() * sh
        root.geometry('%dx%d+%d+%d' % (w, h, x, y))

        path = "h.png"
        message = "I mean its alright like"
        tk.Label(root, text=message, width=120, height=20).pack()

        root.protocol("WM_DELETE_WINDOW", lambda arg=root: on_closing(arg))


    root = tk.Tk()
    root.title("Csandor")
    message = "I mean it's alright like"
    tk.Label(root, text=message).pack()
    root.geometry("450x250")
    root.protocol("WM_DELETE_WINDOW", lambda arg=root: on_closing(arg))
    root.mainloop()